name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Generate Wrapper
      run: gradle wrapper
      
    - name: Clean
      run: ./gradlew clean
      
    - name: Build Release APK **MIGLIORE**
      run: ./gradlew assembleRelease
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: CalorieFoto-Release.apk
        path: app/build/outputs/apk/release/app-release.apk
